name: macOS 11

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: macos-11
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Brew Update
        run: |
            brew update
            brew --version

      - name: Setup Homebrew Tap
        run: |
            mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
            cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade

      - name: Run Brew Cask Upgrade
        run: brew cu -y -a --no-brew-update

  pinning-workflow:
    runs-on: macos-11
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Brew Update
        run: |
          brew update
          brew --version

      - name: Setup Homebrew Tap
        run: |
          mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
          cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade

      - name: Verify cask is reporting outdated
        run: brew cu --all google-chrome --report-only || test $? -eq 1

      - name: Pin google-chrome
        run: brew cu pin google-chrome

      - name: Verify it is not reporting outdated
        run: brew cu --all google-chrome --report-only

      - name: Unpin google-chrome
        run: brew cu unpin google-chrome

      - name: Verify it is reporting outdated
        run: brew cu --all google-chrome --report-only || test $? -eq 1
