name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  upgrade:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Brew Update
        run: |
            brew update
            brew --version

      - name: Setup Homebrew Tap
        run: |
            mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
            cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade

      - name: Run Brew Cask Upgrade
        run: brew cu -y -a --no-brew-update

      - name: Check no reported updates
        run: brew cu -y -a --no-brew-update --report-only

  pinning-workflow:
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Brew Update
        run: |
          brew update
          brew --version

      - name: Setup Homebrew Tap
        run: |
          mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
          cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade

      - name: Verify cask is reporting outdated
        run: brew cu --all google-chrome --report-only || test $? -eq 1

      - name: Pin google-chrome
        run: brew cu pin google-chrome

      - name: Verify it is not reporting outdated
        run: brew cu --all google-chrome --report-only

      - name: Unpin google-chrome
        run: brew cu unpin google-chrome

      - name: Verify it is reporting outdated
        run: brew cu --all google-chrome --report-only || test $? -eq 1

  pinned-export-workflow:
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Brew Update
        run: |
          brew update
          brew --version

      - name: Setup Homebrew Tap
        run: |
          mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
          cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade

      - name: Pin google-chrome
        run: brew cu pin google-chrome

      - name: Export pinned casks
        run: brew cu pinned --export exported.txt

      - name: Setup expected file
        run: echo "google-chrome" > expected.txt

      - name: Verify exported file is as expected
        run: cmp exported.txt expected.txt

  pinned-load-workflow:
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Brew Update
        run: |
          brew update
          brew --version

      - name: Setup Homebrew Tap
        run: |
          mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
          cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade

      - name: Setup backup file
        run: echo "google-chrome" > /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/backup.txt

      - name: Import backup file
        run: brew cu pinned --load /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/backup.txt

      - name: Verify exported file is as expected
        run: cd /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade && cmp pinned backup.txt
